import React, { createContext, useContext, useState, useEffect } from 'react';

const COUNTRY_CURRENCY_STORAGE_KEY = 'country_currency_preference';
const DEFAULT_COUNTRY_CURRENCY_CODE = 'uz';
const COUNTRY_CURRENCY_OPTIONS = [
  {
    code: 'uz',
    flag: '/flags/uz.svg',
    nameRu: 'Узбекистан',
    nameUz: "O'zbekiston",
    currencyRu: 'сум',
    currencyUz: "so'm"
  },
  {
    code: 'kz',
    flag: '/flags/kz.svg',
    nameRu: 'Казахстан',
    nameUz: "Qozog'iston",
    currencyRu: 'тенге',
    currencyUz: 'tenge'
  },
  {
    code: 'tm',
    flag: '/flags/tm.svg',
    nameRu: 'Туркменистан',
    nameUz: 'Turkmaniston',
    currencyRu: 'манат',
    currencyUz: 'manat'
  },
  {
    code: 'tj',
    flag: '/flags/tj.svg',
    nameRu: 'Таджикистан',
    nameUz: 'Tojikiston',
    currencyRu: 'сомони',
    currencyUz: 'somoni'
  },
  {
    code: 'kg',
    flag: '/flags/kg.svg',
    nameRu: 'Кыргызстан',
    nameUz: "Qirg'iziston",
    currencyRu: 'сом',
    currencyUz: 'som'
  },
  {
    code: 'af',
    flag: '/flags/af.svg',
    nameRu: 'Афганистан',
    nameUz: "Afg'oniston",
    currencyRu: 'афгани',
    currencyUz: "afg'oni"
  },
  {
    code: 'ru',
    flag: '/flags/ru.svg',
    nameRu: 'Россия',
    nameUz: 'Rossiya',
    currencyRu: 'руб',
    currencyUz: 'rubl'
  }
];
const normalizeCountryCurrencyCode = (value) => {
  const normalized = String(value || '').trim().toLowerCase();
  return COUNTRY_CURRENCY_OPTIONS.some((option) => option.code === normalized)
    ? normalized
    : DEFAULT_COUNTRY_CURRENCY_CODE;
};
const getCountryCurrencyByCode = (code) => (
  COUNTRY_CURRENCY_OPTIONS.find((option) => option.code === code)
  || COUNTRY_CURRENCY_OPTIONS[0]
);

// Translations
const translations = {
  ru: {
    // Common
    loading: 'Загрузка...',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Редактировать',
    add: 'Добавить',
    search: 'Поиск',
    all: 'Все',
    back: 'Назад',
    next: 'Далее',
    sum: 'сум',
    close: 'Закрыть',

    // Navigation
    showcase: 'Витрина',
    menu: 'Меню',
    favorites: 'Избранные',
    cart: 'Корзина',
    reservations: 'Бронирование',
    orders: 'Заказы',
    feedback: 'Жалобы',

    // Navbar
    operatorPanel: 'Панель оператора',
    controlPanel: 'Панель управления',
    switchRestaurant: 'Сменить магазин',
    broadcast: 'Рассылка',
    superAdmin: 'Супер-админ',
    logout: 'Выйти',
    selectRestaurant: 'Выберите магазин для работы.',
    useRestaurantMenu: 'Нажмите на логотип или название магазина выше, чтобы выбрать другой магазин.',
    restaurantSwitched: 'Магазин переключен',

    // Catalog
    catalog: 'Каталог',
    addToCart: 'В корзину',
    outOfStock: 'Нет в наличии',

    // Cart
    cartEmpty: 'Корзина пуста',
    cartEmptyDesc: 'Добавьте товары из каталога',
    goToCatalog: 'Перейти в каталог',
    yourOrder: 'Ваш заказ',
    delivery: 'Доставка',
    comment: 'Комментарий к заказу',
    commentPlaceholder: 'Пожелания к заказу...',
    deliveryPoint: 'Точка доставки',
    changePoint: 'Изменить точку',
    specifyLocation: 'Указать местоположение',
    phone: 'Телефон',
    deliveryTime: 'Время доставки',
    asap: 'Быстрее',
    scheduled: 'Ко времени',
    paymentMethod: 'Способ оплаты',
    cash: 'Наличные',
    card: 'Карта',
    total: 'Итого',
    checkout: 'Оформить',
    location: 'Местоположение',
    detectLocation: 'Определить',

    // Orders
    myOrders: 'Мои заказы',
    noOrders: 'У вас пока нет заказов',
    makeFirstOrder: 'Сделайте ваш первый заказ!',
    orderComposition: 'Состав заказа',
    payment: 'Оплата',
    cancelOrder: 'Отменить заказ',
    cancelling: 'Отмена...',
    expand: 'Подробнее',
    collapse: 'Свернуть',

    // Statuses
    statusNew: 'Новый',
    statusPreparing: 'Готовится',
    statusDelivering: 'Доставляется',
    statusDelivered: 'Доставлен',
    statusCancelled: 'Отменен',

    // Admin
    dashboard: 'Аналитика',
    products: 'Товары',
    categories: 'Категории',
    containers: 'Фасовка',
    clients: 'Клиенты',
    users: 'Пользователи',
    restaurants: 'Магазины',
    settings: 'Настройки',
    operators: 'Операторы',
    logs: 'Логи',
    activityLog: 'Журнал действий',
    superAdminDashboard: 'Панели Супер-админа',
    balance: 'Баланс',
    accountBalance: 'Баланс счета',
    currentBalance: 'Текущий баланс',
    orderCost: 'Стоимость заказа',
    paymentInfo: 'Данные для оплаты',
    incomes: 'Поступления',
    expenses: 'Списания',
    bankCard: 'Банковская карта',
    cardNumber: 'Номер карты',
    cardHolder: 'Владелец карты',
    phoneNumber: 'Номер телефона',
    supportTitle: 'Связь с администратором',
    topupInstruction: 'Для пополнения баланса переведите сумму по указанным реквизитам и отправьте квитанцию администратору в Telegram. После подтверждения баланс будет пополнен автоматически.',
    freeTier: 'Бесплатный тариф',
    activeSchedule: 'Активное расписание',
    dateAndTime: 'Дата и время',
    recurrence: 'Повтор',
    once: 'Один раз',
    everyDay: 'Каждый день',
    everyWeek: 'Каждую неделю',
    customDays: 'По выбранным дням',
    selectDays: 'В какие дни:',
    date: 'Дата',
    time: 'Время',

    // Dashboard
    revenue: 'Выручка',
    averageCheck: 'Средний чек',
    ordersCount: 'Количество заказов',
    topProducts: 'Топ популярных товаров',
    topCustomers: 'Топ клиентов',
    orderGeography: 'География заказов',
    year: 'Год',
    month: 'Месяц',
    quantity: 'Кол-во',
    noDataForPeriod: 'Нет данных за выбранный период',
    noData: 'Нет данных',

    // Yearly Analytics
    yearlyAnalytics: 'Годовая аналитика за',
    yearSuffix: 'год',
    revenueForYear: 'Выручка за год',
    ordersForYear: 'Заказов за год',
    avgCheckForYear: 'Средний чек за год',
    financeByMonths: 'Финансы по месяцам',
    deliveredOrdersByMonths: 'Доставленные заказы по месяцам',
    top5ByMonths: 'Топ-5 товаров по месяцам',

    // Month names
    monthJan: 'Январь',
    monthFeb: 'Февраль',
    monthMar: 'Март',
    monthApr: 'Апрель',
    monthMay: 'Май',
    monthJun: 'Июнь',
    monthJul: 'Июль',
    monthAug: 'Август',
    monthSep: 'Сентябрь',
    monthOct: 'Октябрь',
    monthNov: 'Ноябрь',
    monthDec: 'Декабрь',

    // Month short names
    monthShortJan: 'Янв',
    monthShortFeb: 'Фев',
    monthShortMar: 'Мар',
    monthShortApr: 'Апр',
    monthShortMay: 'Май',
    monthShortJun: 'Июн',
    monthShortJul: 'Июл',
    monthShortAug: 'Авг',
    monthShortSep: 'Сен',
    monthShortOct: 'Окт',
    monthShortNov: 'Ноя',
    monthShortDec: 'Дек',

    // Products
    productName: 'Название',
    category: 'Категория',
    price: 'Цена',
    status: 'Статус',
    actions: 'Действия',
    active: 'Активен',
    hidden: 'Скрыт',
    addProduct: 'Добавить товар',
    importExcel: 'Импорт Excel',
    downloadExcel: 'Скачать Excel',
    duplicate: 'Дублировать',
    photo: 'Фото',
    allCategories: 'Все категории',
    allStatuses: 'Все статусы',
    activeProducts: 'Активные',
    hiddenProducts: 'Скрытые',
    found: 'Найдено',
    of: 'из',
    searchByName: 'Поиск по названию...',
    selectedProducts: 'Выбрано товаров',
    deleteSelected: 'Удалить выбранные',
    sortOrder: 'Порядок',

    // Orders Admin
    orderNumber: 'Номер',
    client: 'Клиент',
    amount: 'Сумма',
    details: 'Детали',

    // Order Modal
    orderHash: 'Заказ #',
    phoneLabel: 'Телефон:',
    clientLabel: 'Клиент:',
    addressLabel: 'Адрес:',
    amountLabel: 'Сумма:',
    call: 'Позвонить',
    yandexMaps: 'Яндекс.Карты',
    googleMaps: 'Google Maps',
    yandexTaxi: 'Яндекс Go',
    myTaxi: 'My Taxi',
    navigator: 'Навигатор',
    cancelledBy: 'Отменил:',
    processedBy: 'Обработал:',
    cancelReason: 'Причина отмены:',
    orderStatus: 'Статус заказа:',
    addProductToOrder: 'Добавить товар:',
    selectProduct: 'Выберите товар...',
    newAmount: 'Новая сумма:',

    // Cancel Order Modal
    cancelOrderTitle: 'Отмена заказа',
    cancelOrderConfirm: 'Вы уверены, что хотите отменить этот заказ? Укажите причину отмены:',
    cancelReasonLabel: 'Причина отмены',
    cancelReasonPlaceholder: 'Например: клиент отказался, нет товара в наличии, ошибка в заказе...',

    // Product Modal
    editProduct: 'Редактировать товар',
    nameRu: 'Название (RU) *',
    nameUz: 'Название (UZ)',
    descriptionRu: 'Описание (RU)',
    descriptionUz: 'Описание (UZ)',
    priceSum: 'Цена ({sum}) *',
    unit: 'Единица измерения *',
    unitPcs: 'шт',
    unitPortion: 'порция',
    unitKg: 'кг',
    unitL: 'л',
    unitG: 'г',
    unitMl: 'мл',
    unitCup: 'Стакан',
    unitJar: 'Банка',
    unitPack: 'Пачка',
    unitBlock: 'Блок',
    unitCm: 'см',
    unitM: 'м',
    unitM2: 'м2',
    unitM3: 'м3',
    unitKm: 'км',
    unitT: 'т',
    orderStepLabel: 'Шаг заказа (кг)',
    orderStepNote: 'Если указать 0,25, клиент будет добавлять товар по 0,25 кг за одно нажатие.',
    containerLabel: 'Фасовка',
    noContainer: 'Без посуды',
    containerCostNote: 'Стоимость посуды добавится к заказу',
    containerNormLabel: 'Норма посуды',
    containerNormNote: 'Сколько единиц товара помещается в 1 посуду (например 4)',
    image: 'Изображение',
    removeImage: 'Удалить',
    pasteImage: 'Вставьте изображение (Ctrl+V)',
    orDragFile: 'или перетащите файл сюда',
    uploadingImage: 'Загрузка изображения...',
    orEnterUrl: 'Или введите URL:',
    hideProduct: 'Скрыть товар',
    hideProductNote: 'Если включено — товар не будет показываться клиентам.',
    selectCategory: 'Выберите категорию',
    selectSubcategory: 'Выберите подкатегорию',
    categoryRequired: 'Категория *',
    subcategoryLevel: 'Подкатегория уровня',

    // Containers
    noContainersAdded: 'Нет добавленной посуды',
    containerDesc: 'Посуда привязывается к товарам. Её стоимость автоматически добавляется к заказу.',
    editContainer: 'Редактировать посуду',
    addContainer: 'Добавить посуду',
    containerName: 'Название *',
    containerNamePlaceholder: 'Например: Контейнер 1л, Стакан 0.5л',
    containerPrice: 'Цена ({sum}) *',
    sortOrderLabel: 'Порядок сортировки',

    // Feedback
    feedbackTab: 'Обратная связь',
    customerAppeals: 'Обращения клиентов',
    allTypes: 'Все типы',
    complaint: 'Жалоба',
    suggestion: 'Предложение',
    question: 'Вопрос',
    other: 'Другое',
    inProgress: 'В работе',
    resolved: 'Решено',
    closed: 'Закрыто',
    noAppeals: 'Обращений пока нет',
    type: 'Тип',
    message: 'Сообщение',
    view: 'Просмотр',
    appealHash: 'Обращение #',
    customerMessage: 'Сообщение клиента:',
    yourResponse: 'Ваш ответ:',
    responsePlaceholder: 'Введите ответ на обращение...',
    takeInProgress: 'Взять в работу',

    // Broadcast Modal
    broadcastTitle: 'Рассылка уведомлений',
    broadcastInfo: 'Сообщение будет отправлено всем клиентам, которые делали заказы в вашем магазине.',
    broadcastPhoto: 'Фото (необязательно)',
    broadcastMedia: 'Фото/видео (необязательно)',
    deletePhoto: 'Удалить фото',
    deleteVideo: 'Удалить видео',
    broadcastPasteOrSelectMedia: 'Вставьте изображение (Ctrl+V), перетащите файл или нажмите для выбора',
    broadcastPasteImage: 'Вставьте изображение (Ctrl+V)',
    broadcastDragFile: 'или перетащите файл сюда',
    messageText: 'Текст сообщения *',
    messagePlaceholder: 'Напишите текст рассылки...',
    formattingSupport: 'Поддерживается форматирование:',
    bold: 'жирный',
    italic: 'курсив',
    preview: 'Предпросмотр:',
    restaurant: 'Магазин',
    messageTextPreview: 'Текст сообщения...',
    sending: 'Отправка...',
    sendBroadcast: 'Отправить рассылку',

    // Excel Import Modal
    excelImportTitle: 'Импорт товаров из Excel',
    excelFormatTitle: 'Формат файла:',
    excelFormatDesc: 'Первая строка — заголовки столбцов. Обязательные столбцы:',
    excelColName: 'Название (RU)',
    excelColNameAlt: 'Название',
    excelColNameDesc: '— название товара',
    excelColPrice: 'Цена',
    excelColPriceDesc: '— цена товара',
    excelOptionalCols: 'Дополнительные столбцы:',
    excelColCategory: 'Категория',
    excelColCategoryDesc: '— название категории',
    excelColNameUz: 'Название (UZ)',
    excelColNameUzDesc: '— название на узбекском',
    excelColUnit: 'Единица',
    excelColUnitDesc: '— единица измерения (шт, кг, порция и т.д.)',
    selectExcelFile: 'Выберите файл Excel (.xlsx, .xls, .csv)',
    previewFirst10: 'Предпросмотр (первые 10 строк):',
    column: 'Столбец',
    importing: 'Импорт...',
    importAction: 'Импортировать',

    // Image Preview
    imagePreview: 'Просмотр изображения',

    // Blocked user
    accountBlocked: 'Ваш аккаунт заблокирован',
    contactSupport: 'Связаться с поддержкой',

    // Super Admin Dashboard
    saSubtitle: 'Управление всей сетью',
    saRestaurantsCount: 'Всего магазинов',
    saOperatorsCount: 'Операторов',
    saCustomersCount: 'Клиентов',
    saNewOrdersCount: 'Новых заказов',
    saManageRestaurants: 'Управление магазинами',
    saAddRestaurant: 'Добавить магазин',
    saTableLogo: 'Лого',
    saTableName: 'Название',
    saTableProducts: 'Товары',
    saTableAddress: 'Адрес',
    saTableZone: 'Зона',
    saTableBot: 'Бот',
    saTableStatus: 'Статус',
    saTableActions: 'Действия',
    saEmptyRestaurants: 'Магазины не найдены',
    saManageOperators: 'Управление операторами',
    saAddOperator: 'Добавить оператора',
    saTableLogin: 'Логин',
    saTableFio: 'ФИО',
    saTablePhone: 'Телефон',
    saTableRole: 'Роль',
    saEmptyOperators: 'Операторы не найдены',
    saListCustomers: 'Список клиентов',
    saAllShops: 'Все магазины',
    saAllRoles: 'Все роли',
    saAllStatuses: 'Все статусы',
    saRoleOperator: 'Оператор',
    saRoleSuperadmin: 'Супер-админ',
    saStatusActive: 'Активен',
    saStatusInactive: 'Неактивен',
    saStatusBlocked: 'Заблокирован',
    saSearch: 'Поиск...',
    saSearchShop: 'Поиск магазина...',
    saSearchNamePhone: 'Имя или телефон...',
    saTableUser: 'Пользователь',
    saTableShop: 'Магазин',
    saTableOrders: 'Заказов',
    saTableSum: 'Сумма',
    saEmptyCustomers: 'Клиенты не найдены',
    saManageCategories: 'Управление категориями',
    saLevels: 'Многоуровневая структура',
    saMainLevel: 'Главный уровень',
    saLevel: 'Уровень',
    saSelectParent: 'Выберите родительскую категорию для просмотра',
    saEmptyLevel: 'На этом уровне пока нет категорий',
    saAllUsers: 'Все пользователи',
    saAllActions: 'Все действия',
    saTableDate: 'Дата',
    saTableAction: 'Действие',
    saTableObject: 'Объект',
    saTableRestaurant: 'Магазин',
    saEmptyLogs: 'Логов не найдено',
    saModalEditRestaurant: 'Редактировать магазин',
    saModalNewRestaurant: 'Новый магазин',
    saLogo: 'Логотип',
    saWorkingHours: 'Часы работы',
    saStartTime: 'Время начала',
    saEndTime: 'Время окончания',
    saTgSettings: 'Настройки Telegram',
    saGroupNoticeIds: 'ID группы для уведомлений',
    saSupportUsername: 'Username поддержки',
    saPaymentMethods: 'Способы оплаты',
    saServiceFee: 'Сбор за обслуживание',
    saDeliverySettings: 'Настройки доставки',
    saBaseRadius: 'Базовый радиус (км)',
    saBasePrice: 'Базовая цена',
    saPricePerKm: 'Цена за км',
    saCoordinates: 'Координаты',
    saCancel: 'Отмена',
    saSave: 'Сохранить',
    saDone: 'Готово',
    saShow: 'Показать по:',
    saShown: 'Показано',
    saOf: 'из',
    saRecords: 'записей',
    saTableBalance: 'Баланс',
    saTableTier: 'Тариф',
    billingSettings: 'Биллинг',
    billingGlobalSettings: 'Глобальные настройки биллинга',
    saveSettings: 'Сохранить настройки',
    paymentRequisitesInfo: 'Платежные реквизиты (для операторов)',
    defaultFinancialParams: 'Дефолтные финансовые параметры',
    defaultStartingBalance: 'Начальный баланс новых магазинов',
    defaultOrderCost: 'Сбор за 1 заказ по умолчанию',
    topupRestaurantBalance: 'Пополнение баланса магазина',
    amountToTopup: 'Сумма пополнения',
    topupDescription: 'Примечание к платежу',
    topupAction: 'Пополнить баланс',

    editOperator: 'Редактировать оператора',
    newOperator: 'Новый оператор',
  },
  uz: {
    // Common
    loading: 'Yuklanmoqda...',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    delete: "O'chirish",
    edit: 'Tahrirlash',
    add: "Qo'shish",
    search: 'Qidirish',
    all: 'Hammasi',
    back: 'Orqaga',
    next: 'Keyingi',
    sum: "so'm",
    close: 'Yopish',

    // Navigation
    showcase: 'Vitrina',
    menu: 'Menyu',
    favorites: 'Saralanganlar',
    cart: 'Savat',
    reservations: 'Bron',
    orders: 'Buyurtmalar',
    feedback: 'Shikoyat',

    // Navbar
    operatorPanel: 'Operator paneli',
    controlPanel: 'Boshqaruv paneli',
    switchRestaurant: "Do'konni almashtirish",
    broadcast: 'Xabarnoma',
    superAdmin: 'Super-admin',
    logout: 'Chiqish',
    selectRestaurant: "Ish uchun do'kon tanlang.",
    useRestaurantMenu: "Boshqa do'konni tanlash uchun yuqoridagi logotip yoki do'kon nomini bosing.",
    restaurantSwitched: "Do'kon almashtirildi",

    // Catalog
    catalog: 'Katalog',
    addToCart: 'Savatga',
    outOfStock: 'Mavjud emas',

    // Cart
    cartEmpty: 'Savat bo\'sh',
    cartEmptyDesc: 'Katalogdan mahsulot qo\'shing',
    goToCatalog: 'Katalogga o\'tish',
    yourOrder: 'Sizning buyurtmangiz',
    delivery: 'Yetkazib berish',
    comment: 'Buyurtmaga izoh',
    commentPlaceholder: 'Buyurtma uchun istaklar...',
    deliveryPoint: 'Yetkazib berish nuqtasi',
    changePoint: 'Nuqtani o\'zgartirish',
    specifyLocation: 'Joylashuvni ko\'rsatish',
    phone: 'Telefon',
    deliveryTime: 'Yetkazib berish vaqti',
    asap: 'Tezroq',
    scheduled: 'Vaqtga',
    paymentMethod: 'To\'lov usuli',
    cash: 'Naqd pul',
    card: 'Karta',
    total: 'Jami',
    checkout: 'Buyurtma berish',
    location: 'Joylashuv',
    detectLocation: 'Aniqlash',

    // Orders
    myOrders: 'Mening buyurtmalarim',
    noOrders: 'Sizda hali buyurtmalar yo\'q',
    makeFirstOrder: 'Birinchi buyurtmangizni bering!',
    orderComposition: 'Buyurtma tarkibi',
    payment: 'To\'lov',
    cancelOrder: 'Buyurtmani bekor qilish',
    cancelling: 'Bekor qilinmoqda...',
    expand: 'Batafsil',
    collapse: 'Yig\'ish',

    // Statuses
    statusNew: 'Yangi',
    statusPreparing: 'Tayyorlanmoqda',
    statusDelivering: 'Yetkazilmoqda',
    statusDelivered: 'Yetkazildi',
    statusCancelled: 'Bekor qilindi',

    // Admin
    dashboard: 'Analitika',
    products: 'Mahsulotlar',
    categories: 'Kategoriyalar',
    containers: 'Fasovka',
    clients: 'Mijozlar',
    users: 'Foydalanuvchilar',
    restaurants: "Do'konlar",
    settings: 'Sozlamalar',
    operators: 'Operatorlar',
    logs: 'Loglar',
    activityLog: 'Harakatlar jurnali',
    superAdminDashboard: 'Super-admin paneli',
    balance: 'Balans',
    accountBalance: 'Hisob balansi',
    currentBalance: 'Joriy balans',
    orderCost: 'Buyurtma narxi',
    paymentInfo: "To'lov ma'lumotlari",
    incomes: 'Tushumlar',
    expenses: 'Chiqimlar',
    bankCard: 'Bank kartasi',
    cardNumber: 'Karta raqami',
    cardHolder: 'Karta egasi',
    phoneNumber: 'Telefon raqami',
    supportTitle: "Admin bilan bog'lanish",
    topupInstruction: "Balansni to'ldirish uchun ko'rsatilgan rekvizitlarga pul o'tkazing va chekni Telegram orqali adminga yuboring. Tasdiqlangandan so'ng balans avtomatik ravishably to'ldiriladi.",
    freeTier: 'Bepul tarif',
    activeSchedule: 'Faol reja',
    dateAndTime: 'Sana va vaqt',
    recurrence: 'Takrorlash',
    once: 'Bir marta',
    everyDay: 'Har kuni',
    everyWeek: 'Har hafta',
    customDays: 'Tanlangan kunlarda',
    selectDays: 'Qaysi kunlarda:',
    date: 'Sana',
    time: 'Vaqt',

    // Dashboard
    revenue: 'Daromad',
    averageCheck: 'O\'rtacha chek',
    ordersCount: 'Buyurtmalar soni',
    topProducts: 'Mashhur mahsulotlar',
    topCustomers: 'Top mijozlar',
    orderGeography: 'Buyurtmalar geografiyasi',
    year: 'Yil',
    month: 'Oy',
    quantity: 'Soni',
    noDataForPeriod: 'Tanlangan davr uchun maʼlumot yoʻq',
    noData: 'Maʼlumot yoʻq',

    // Yearly Analytics
    yearlyAnalytics: 'Yillik analitika',
    yearSuffix: 'yil',
    revenueForYear: 'Yillik daromad',
    ordersForYear: 'Yillik buyurtmalar',
    avgCheckForYear: 'Yillik o\'rtacha chek',
    financeByMonths: 'Oylar bo\'yicha moliya',
    deliveredOrdersByMonths: 'Oylar bo\'yicha yetkazilgan buyurtmalar',
    top5ByMonths: 'Oylar bo\'yicha top-5 mahsulotlar',

    // Month names
    monthJan: 'Yanvar',
    monthFeb: 'Fevral',
    monthMar: 'Mart',
    monthApr: 'Aprel',
    monthMay: 'May',
    monthJun: 'Iyun',
    monthJul: 'Iyul',
    monthAug: 'Avgust',
    monthSep: 'Sentabr',
    monthOct: 'Oktabr',
    monthNov: 'Noyabr',
    monthDec: 'Dekabr',

    // Month short names
    monthShortJan: 'Yan',
    monthShortFeb: 'Fev',
    monthShortMar: 'Mar',
    monthShortApr: 'Apr',
    monthShortMay: 'May',
    monthShortJun: 'Iyn',
    monthShortJul: 'Iyl',
    monthShortAug: 'Avg',
    monthShortSep: 'Sen',
    monthShortOct: 'Okt',
    monthShortNov: 'Noy',
    monthShortDec: 'Dek',

    // Products
    productName: 'Nomi',
    category: 'Kategoriya',
    price: 'Narx',
    status: 'Holat',
    actions: 'Amallar',
    active: 'Faol',
    hidden: 'Yashirin',
    addProduct: 'Mahsulot qo\'shish',
    importExcel: 'Excel import',
    downloadExcel: 'Excel yuklab olish',
    duplicate: 'Nusxa olish',
    photo: 'Rasm',
    allCategories: 'Barcha kategoriyalar',
    allStatuses: 'Barcha holatlar',
    activeProducts: 'Faol',
    hiddenProducts: 'Yashirin',
    found: 'Topildi',
    of: 'dan',
    searchByName: 'Nomi bo\'yicha qidirish...',
    selectedProducts: 'Tanlangan mahsulotlar',
    deleteSelected: 'Tanlanganlarni o\'chirish',
    sortOrder: 'Tartibi',

    // Orders Admin
    orderNumber: 'Raqam',
    client: 'Mijoz',
    amount: 'Summa',
    details: 'Tafsilotlar',

    // Order Modal
    orderHash: 'Buyurtma #',
    phoneLabel: 'Telefon:',
    clientLabel: 'Mijoz:',
    addressLabel: 'Manzil:',
    amountLabel: 'Summa:',
    call: 'Qo\'ng\'iroq qilish',
    yandexMaps: 'Yandex.Xaritalar',
    googleMaps: 'Google Maps',
    yandexTaxi: 'Yandex Go',
    myTaxi: 'My Taxi',
    navigator: 'Navigator',
    cancelledBy: 'Bekor qilgan:',
    processedBy: 'Qayta ishlagan:',
    cancelReason: 'Bekor qilish sababi:',
    orderStatus: 'Buyurtma holati:',
    addProductToOrder: 'Mahsulot qo\'shish:',
    selectProduct: 'Mahsulot tanlang...',
    newAmount: 'Yangi summa:',

    // Cancel Order Modal
    cancelOrderTitle: 'Buyurtmani bekor qilish',
    cancelOrderConfirm: 'Ushbu buyurtmani bekor qilmoqchimisiz? Bekor qilish sababini ko\'rsating:',
    cancelReasonLabel: 'Bekor qilish sababi',
    cancelReasonPlaceholder: 'Masalan: mijoz rad etdi, mahsulot mavjud emas, buyurtmada xatolik...',

    // Product Modal
    editProduct: 'Mahsulotni tahrirlash',
    nameRu: 'Nomi (RU) *',
    nameUz: 'Nomi (UZ)',
    descriptionRu: 'Tavsif (RU)',
    descriptionUz: 'Tavsif (UZ)',
    priceSum: 'Narxi ({sum}) *',
    unit: 'O\'lchov birligi *',
    unitPcs: 'dona',
    unitPortion: 'porsiya',
    unitKg: 'kg',
    unitL: 'l',
    unitG: 'g',
    unitMl: 'ml',
    unitCup: 'Stakan',
    unitJar: 'Banka',
    unitPack: 'Pachka',
    unitBlock: 'Blok',
    unitCm: 'sm',
    unitM: 'm',
    unitM2: 'm2',
    unitM3: 'm3',
    unitKm: 'km',
    unitT: 't',
    orderStepLabel: 'Buyurtma qadami (kg)',
    orderStepNote: 'Masalan 0,25 kiritsangiz, mijoz har bosganda 0,25 kg qo‘shiladi.',
    containerLabel: 'Fasovka',
    noContainer: 'Idishsiz',
    containerCostNote: 'Idish narxi buyurtmaga qo\'shiladi',
    containerNormLabel: 'Idish normasi',
    containerNormNote: '1 ta idishga nechta mahsulot sig\'adi (masalan 4)',
    image: 'Rasm',
    removeImage: 'O\'chirish',
    pasteImage: 'Rasmni joylashtiring (Ctrl+V)',
    orDragFile: 'yoki faylni bu yerga torting',
    uploadingImage: 'Rasm yuklanmoqda...',
    orEnterUrl: 'Yoki URL kiriting:',
    hideProduct: 'Mahsulotni yashirish',
    hideProductNote: 'Yoqilgan bo\'lsa — mahsulot mijozlarga ko\'rsatilmaydi.',
    selectCategory: 'Kategoriyani tanlang',
    selectSubcategory: 'Subkategoriyani tanlang',
    categoryRequired: 'Kategoriya *',
    subcategoryLevel: 'Subkategoriya darajasi',

    // Containers
    noContainersAdded: 'Idishlar qo\'shilmagan',
    containerDesc: 'Idish mahsulotlarga biriktiriladi. Uning narxi buyurtmaga avtomatik qo\'shiladi.',
    editContainer: 'Idishni tahrirlash',
    addContainer: 'Idish qo\'shish',
    containerName: 'Nomi *',
    containerNamePlaceholder: 'Masalan: Konteyner 1l, Stakan 0.5l',
    containerPrice: 'Narxi ({sum}) *',
    sortOrderLabel: 'Tartiblash tartibi',

    // Feedback
    feedbackTab: 'Aloqa',
    customerAppeals: 'Mijozlar murojaatlari',
    allTypes: 'Barcha turlar',
    complaint: 'Shikoyat',
    suggestion: 'Taklif',
    question: 'Savol',
    other: 'Boshqa',
    inProgress: 'Jarayonda',
    resolved: 'Hal qilindi',
    closed: 'Yopildi',
    noAppeals: 'Hozircha murojaatlar yo\'q',
    type: 'Turi',
    message: 'Xabar',
    view: 'Ko\'rish',
    appealHash: 'Murojaat #',
    customerMessage: 'Mijoz xabari:',
    yourResponse: 'Sizning javobingiz:',
    responsePlaceholder: 'Murojaatga javob kiriting...',
    takeInProgress: 'Ishga olish',

    // Broadcast Modal
    broadcastTitle: 'Bildirishnoma yuborish',
    broadcastInfo: "Xabar do'koningizda buyurtma bergan barcha mijozlarga yuboriladi.",
    broadcastPhoto: 'Rasm (ixtiyoriy)',
    broadcastMedia: 'Rasm/video (ixtiyoriy)',
    deletePhoto: 'Rasmni o\'chirish',
    deleteVideo: 'Videoni o\'chirish',
    broadcastPasteOrSelectMedia: 'Rasmni joylashtiring (Ctrl+V), faylni torting yoki tanlash uchun bosing',
    broadcastPasteImage: 'Rasmni joylashtiring (Ctrl+V)',
    broadcastDragFile: 'yoki faylni bu yerga torting',
    messageText: 'Xabar matni *',
    messagePlaceholder: 'Xabarnoma matnini yozing...',
    formattingSupport: 'Formatlash qo\'llab-quvvatlanadi:',
    bold: 'qalin',
    italic: 'kursiv',
    preview: 'Oldindan ko\'rish:',
    restaurant: "Do'kon",
    messageTextPreview: 'Xabar matni...',
    sending: 'Yuborilmoqda...',
    sendBroadcast: 'Xabarnomani yuborish',

    // Excel Import Modal
    excelImportTitle: 'Exceldan mahsulotlarni import qilish',
    excelFormatTitle: 'Fayl formati:',
    excelFormatDesc: 'Birinchi qator — ustun sarlavhalari. Majburiy ustunlar:',
    excelColName: 'Nomi (RU)',
    excelColNameAlt: 'Nomi',
    excelColNameDesc: '— mahsulot nomi',
    excelColPrice: 'Narxi',
    excelColPriceDesc: '— mahsulot narxi',
    excelOptionalCols: 'Qo\'shimcha ustunlar:',
    excelColCategory: 'Kategoriya',
    excelColCategoryDesc: '— kategoriya nomi',
    excelColNameUz: 'Nomi (UZ)',
    excelColNameUzDesc: '— o\'zbekcha nomi',
    excelColUnit: 'Birlik',
    excelColUnitDesc: '— o\'lchov birligi (dona, kg, porsiya va h.k.)',
    selectExcelFile: 'Excel faylni tanlang (.xlsx, .xls, .csv)',
    previewFirst10: 'Oldindan ko\'rish (dastlabki 10 qator):',
    column: 'Ustun',
    importing: 'Import...',
    importAction: 'Import qilish',

    // Image Preview
    imagePreview: 'Rasmni ko\'rish',

    // Blocked user
    accountBlocked: 'Sizning akkauntingiz bloklangan',
    contactSupport: 'Qo\'llab-quvvatlash bilan bog\'lanish',

    // Super Admin Dashboard
    saSubtitle: 'Butun tarmog\'ni boshqarish',
    saRestaurantsCount: "Jami do'konlar",
    saOperatorsCount: 'Operatorlar',
    saCustomersCount: 'Mijozlar',
    saNewOrdersCount: 'Yangi buyurtmalar',
    saManageRestaurants: "Do'konlarni boshqarish",
    saAddRestaurant: "Do'kon qo'shish",
    saTableLogo: 'Logo',
    saTableName: 'Nomi',
    saTableProducts: 'Mahsulotlar',
    saTableAddress: 'Manzil',
    saTableZone: 'Zona',
    saTableBot: 'Bot',
    saTableStatus: 'Holat',
    saTableActions: 'Amallar',
    saEmptyRestaurants: "Do'konlar topilmadi",
    saManageOperators: 'Operatorlarni boshqarish',
    saAddOperator: 'Operator qo\'shish',
    saTableLogin: 'Login',
    saTableFio: 'F.I.SH.',
    saTablePhone: 'Telefon',
    saTableRole: 'Rol',
    saEmptyOperators: 'Operatorlar topilmadi',
    saListCustomers: 'Mijozlar ro\'yxati',
    saAllShops: 'Barcha do\'konlar',
    saAllRoles: 'Barcha rollar',
    saAllStatuses: 'Barcha holatlar',
    saRoleOperator: 'Operator',
    saRoleSuperadmin: 'Super-admin',
    saStatusActive: 'Faol',
    saStatusInactive: 'Nofaol',
    saStatusBlocked: 'Bloklangan',
    saSearch: 'Qidirish...',
    saSearchShop: 'Do\'kon qidirish...',
    saSearchNamePhone: 'Ism yoki telefon...',
    saTableUser: 'Foydalanuvchi',
    saTableShop: 'Do\'kon',
    saTableOrders: 'Buyurtmalar',
    saTableSum: 'Summa',
    saEmptyCustomers: 'Mijozlar topilmadi',
    saManageCategories: 'Kategoriyalarni boshqarish',
    saLevels: 'Ko\'p darajali tuzilma',
    saMainLevel: 'Asosiy daraja',
    saLevel: 'Daraja',
    saSelectParent: 'Ko\'rish uchun yuqori kategoriyani tanlang',
    saEmptyLevel: 'Ushbu darajada hali kategoriyalar yo\'q',
    saAllUsers: 'Barcha foydalanuvchilar',
    saAllActions: 'Barcha amallar',
    saTableDate: 'Sana',
    saTableAction: 'Amal',
    saTableObject: 'Obyekt',
    saTableRestaurant: "Do'kon",
    saEmptyLogs: 'Loglar topilmadi',
    saModalEditRestaurant: "Do'konni tahrirlash",
    saModalNewRestaurant: "Yangi do'kon",
    saLogo: 'Logotip',
    saWorkingHours: 'Ish vaqti',
    saStartTime: 'Boshlanish vaqti',
    saEndTime: 'Tugash vaqti',
    saTgSettings: 'Telegram sozламalari',
    saGroupNoticeIds: 'Bildirishnomalar uchun guruh ID',
    saSupportUsername: 'Yordam xizmati username',
    saPaymentMethods: 'To\'lov usullari',
    saServiceFee: 'Xizmat haqi',
    saDeliverySettings: 'Yetkazib berish sozlamalari',
    saBaseRadius: 'Bazaviy radius (km)',
    saBasePrice: 'Bazaviy narx',
    saPricePerKm: 'Har km uchun narx',
    saCoordinates: 'Koordinatalar',
    saCancel: 'Bekor qilish',
    saSave: 'Saqlash',
    saDone: 'Tayyor',
    saShow: 'Ko\'rsatish:',
    saShown: 'Ko\'rsatildi',
    saOf: 'dan',
    saRecords: 'yozuvlar',
    saTableBalance: 'Balans',
    saTableTier: 'Tarif',
    billingSettings: 'Billing',
    billingGlobalSettings: 'Global billing sozlamalari',
    saveSettings: 'Sozlamalarni saqlash',
    paymentRequisitesInfo: 'To\'lov rekvizitlari (operatorlar uchun)',
    defaultFinancialParams: 'Moliyaviy parametrlar (standart)',
    defaultStartingBalance: "Yangi do'konlar uchun boshlang'ich balans",
    defaultOrderCost: 'Har bir buyurtma uchun standart to\'lov',
    topupRestaurantBalance: "Do'kon balansini to'ldirish",
    amountToTopup: "To'ldirish summasi",
    topupDescription: "To'lov izohi",
    topupAction: "Balansni to'ldirish",

    editOperator: 'Operatorni tahrirlash',
    newOperator: 'Yangi operator',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'ru';
  });
  const [countryCurrencyCode, setCountryCurrencyCode] = useState(() => (
    normalizeCountryCurrencyCode(localStorage.getItem(COUNTRY_CURRENCY_STORAGE_KEY))
  ));
  const countryCurrency = getCountryCurrencyByCode(countryCurrencyCode);
  const currencyLabel = language === 'uz'
    ? countryCurrency.currencyUz
    : countryCurrency.currencyRu;

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem(COUNTRY_CURRENCY_STORAGE_KEY, countryCurrencyCode);
  }, [countryCurrencyCode]);

  const t = (key) => {
    if (key === 'sum') return currencyLabel;
    const source = translations[language]?.[key] || translations.ru[key] || key;
    return typeof source === 'string'
      ? source.replaceAll('{sum}', currencyLabel)
      : source;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ru' ? 'uz' : 'ru');
  };

  const setCountryCurrency = (code) => {
    setCountryCurrencyCode(normalizeCountryCurrencyCode(code));
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      toggleLanguage,
      t,
      countryCurrencyCode,
      countryCurrency,
      countryCurrencyOptions: COUNTRY_CURRENCY_OPTIONS,
      setCountryCurrency,
      currencyLabel
    }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
